make re;
echo "test_1ish.txt";
./fillit ./tests/test_1ish.txt;
echo "test_1lsh.txt";
./fillit ./tests/test_1lsh.txt;
echo "test_1osh.txt";
./fillit ./tests/test_1osh.txt;
echo "test_1tsh.txt";
./fillit ./tests/test_1tsh.txt;
echo "test_1zsh.txt";
./fillit ./tests/test_1zsh.txt;
echo "test_2oish.txt";
./fillit ./tests/test_2oish.txt;
echo "test_2iosh.txt";
./fillit ./tests/test_2iosh.txt;
echo "test_4sh.txt";
./fillit ./tests/test_4sh.txt;
echo "test_8sh.txt";
./fillit ./tests/test_8sh.txt;
echo "error_0"
./fillit ./tests/error_0;
echo "error_1"
./fillit ./tests/error_1;
echo "error_2"
./fillit ./tests/error_2;
echo "error_3"
./fillit ./tests/error_3;
echo "error_4"
./fillit ./tests/error_4;
echo "error_5"
./fillit ./tests/error_5;
echo "error_6"
./fillit ./tests/error_6;
echo "error_7"
./fillit ./tests/error_7;
echo "error_8"
./fillit ./tests/error_8;
echo "error_9"
./fillit ./tests/error_9;
echo "error_10"
./fillit ./tests/error_10;
echo "error_11"
./fillit ./tests/error_11;
echo "error_12"
./fillit ./tests/error_12;
echo "error_13"
./fillit ./tests/error_13;
echo "error_14"
./fillit ./tests/error_14;
echo "error_15"
./fillit ./tests/error_15;
echo "error_16"
./fillit ./tests/error_16;
echo "error_17"
./fillit ./tests/error_17;
echo "error_18"
./fillit ./tests/error_18;
echo "error_19"
./fillit ./tests/error_19;
echo "error_20"
./fillit ./tests/error_20;
echo "error_21"
./fillit ./tests/error_21;
echo "error_22"
./fillit ./tests/error_22;
echo "error_23"
./fillit ./tests/error_23;
echo "error_24"
./fillit ./tests/error_24;
echo "error_25"
./fillit ./tests/error_25;
echo "error_26"
./fillit ./tests/error_26;